### PR TITLE
Speed up boot and camera changes

### PR DESCRIPTION
**Pull request by mthomos**

### CODE REVIEW

**Comment by mthomos** [comment]
Also enabling all A53 cores for camera

**Comment by mthomos** [comment]
Use camera flog for Helium

**Comment by mthomos** [comment]
I don't use telegram but try to use HAL1 for telegram ?

**Comment by lineageos-gerrit** [comment]
Hi there;
This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Pull request closed without merging**
